### ISSUE TITLE
Error in Ansible

### ISSUE THREAD

**Issue by boldandbusted** [ITWonderLab/ansible-vbox-vagrant-kubernetes#3]
```
TASK [common/add_packages : Add new repositories keys] *************************
changed: [k8s-m-1] => (item={'key': 'https://download.docker.com/linux/ubuntu/gpg'})
failed: [k8s-m-1] (item={'key': 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'}) => {"ansible_loop_var": "item", "changed": false, "item": {"key": "https://packages.cloud.google.com/apt/doc/apt-key.gpg"}, "msg": "Unable to extract key from '-'", "stderr": "gpg: WARNING: no command supplied.  Trying to guess what you mean ...\ngpg: [don't know]: invalid packet (ctb=0a)\n", "stderr_lines": ["gpg: WARNING: no command supplied.  Trying to guess what you mean ...", "gpg: [don't know]: invalid packet (ctb=0a)"], "stdout": "pub:-:2048:1:FEEA9169307EA071:1614614617:1677728521::-:\nuid:::::::::Rapture Automatic Signing Key (cloud-rapture-signing-key-2021-03-01-08_01_09.pub):\nsub:-:2048:1:AA42F36EE8BEEE0E:1614614617::::\npub:-:2048:1:8B57C5C2836F4BEB:1607040606:1670154510::-:\nuid:::::::::gLinux Rapture Automatic Signing Key (//depot/google3/production/borg/cloud-rapture/keys/cloud-rapture-pubkeys/cloud-rapture-signing-key-2020-12-03-16_08_05.pub) <glinux-team@google.com>:\nsub:-:2048:1:48419E688DD52AC0:1607040606::::\n", "stdout_lines": ["pub:-:2048:1:FEEA9169307EA071:1614614617:1677728521::-:", "uid:::::::::Rapture Automatic Signing Key (cloud-rapture-signing-key-2021-03-01-08_01_09.pub):", "sub:-:2048:1:AA42F36EE8BEEE0E:1614614617::::", "pub:-:2048:1:8B57C5C2836F4BEB:1607040606:1670154510::-:", "uid:::::::::gLinux Rapture Automatic Signing Key (//depot/google3/production/borg/cloud-rapture/keys/cloud-rapture-pubkeys/cloud-rapture-signing-key-2020-12-03-16_08_05.pub) <glinux-team@google.com>:", "sub:-:2048:1:48419E688DD52AC0:1607040606::::"]}
```

My version information:
```
  master U:1  ~/gitrepos/others/ansible-vbox-vagrant-kubernetes                                       13:03:32  ⚡79%  jesseadelman
 1 ❯ ansible --version
ansible [core 2.11.0]
  config file = None
  configured module search path = ['/Users/jesseadelman/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/4.0.0/libexec/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/jesseadelman/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.5 (default, May  4 2021, 03:36:27) [Clang 12.0.0 (clang-1200.0.32.29)]
  jinja version = 3.0.1
  libyaml = True
  master U:1  ~/gitrepos/others/ansible-vbox-vagrant-kubernetes                                       13:07:37  ⚡79%  jesseadelman
❯ vagrant --version
Vagrant 2.2.16
```

Happy to provide more info, more shell output, if you like. :) Thanks.

**Comment by javierruizjimenez** [comment]
@boldandbusted thanks for opening an issue. Unfortunately I have not been able to reproduce the error (please check VirtualBox Internet access - instructions below).

I am running the command `vangrat up` after having upgraded all packages to:

- vagrant: 2.2.16
- virtualbox: 6.1.16
- ansible 2.9.9
- 'bento/ubuntu-20.04' version '202105.25.0' (`vagrant box update` if needed)

I believe the error was an issue with a broken downloaded GPG file 
https://packages.cloud.google.com/apt/doc/apt-key.gpg


        TASK [common/add_packages : Add new repositories keys] *************************
        changed: [k8s-m-1] => (item={'key': 'https://download.docker.com/linux/ubuntu/gpg'})
        changed: [k8s-m-1] => (item={'key': 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'})
        
        TASK [common/add_packages : Add new repositories to sources] *******************
        changed: [k8s-m-1] => (item={'repo': 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable'})
        changed: [k8s-m-1] => (item={'repo': 'deb https://apt.kubernetes.io/ kubernetes-xenial main'})


Could you please check again?

### Access to the Internet from inside a VirtualBox machine

Please check also that you have access to the Internet from inside the VBox machines:

(password is **vagrant**)

    $ ssh vagrant@192.168.50.11
    The authenticity of host '192.168.50.11 (192.168.50.11)' can't be established.
    ECDSA key fingerprint is SHA256:j6zxL49UqzfRcIdpQiPwbpt7t7JuqthrrJBtXDkeEjk.
    Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
    Warning: Permanently added '192.168.50.11' (ECDSA) to the list of known hosts.
    vagrant@192.168.50.11's password: **vagrant**
    Welcome to Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-73-generic x86_64)
    ...
    This system is built by the Bento project by Chef Software
    More information can be found at https://github.com/chef/bento
    Last login: Thu Jun 10 15:40:48 2021 from 10.0.2.2
    
    vagrant@k8s-m-1:~$ ping 8.8.8.8
    PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
    64 bytes from 8.8.8.8: icmp_seq=1 ttl=63 time=2.76 ms
    64 bytes from 8.8.8.8: icmp_seq=2 ttl=63 time=3.03 ms

**Comment by boldandbusted** [comment]
Thank you! It was a local issue with Ansible and Vagrant setups.
